# It contains the configuration for logging
# You can find more info in https://docs.python.org/3/library/logging.config.html#logging-config-api
version: 1
formatters:
  detailed:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
filters:
  warnings_filter:
    (): logging.Filter
    name: "py.warnings"
  info_only_filter:
    (): GANDLF.utils.gandlf_logger.InfoOnlyFilter
handlers:
  stdoutHandler: # only display info level
    class: logging.StreamHandler
    level: INFO
    formatter: detailed
    filters: [info_only_filter]
    stream: ext://sys.stdout
  stderrHandler: # display warning and above messages
    class: logging.StreamHandler
    level: WARNING
    formatter: detailed
    stream: ext://sys.stderr
  debugHandler:
    class: logging.FileHandler
    filename: gandlf.log
    formatter: detailed
    level: DEBUG
loggers: # you can add your customized logger
  debug_logger:
    level: DEBUG
    handlers: [stdoutHandler, debugHandler, stderrHandler]
    propagate: no
root:
  level: DEBUG
  handlers: [stdoutHandler, debugHandler, stderrHandler]
